export const contact = {
    CONTACT_ID: "input[name='Address.AddressID']",
    CONTACT_NAME: "input[name='Address.Name']",
    CONTACT_TYPE_ADD_BUTTON: "div.address-type-grid div[title='Add'] button",
    CONTACT_TYPE_DROPDOWN: "div.address-type-grid input[name='Name']",
    CONTACT_SAVE_BUTTON: "button.save",
    CONTACT_SEARCH_INPUT: "input[title='ID\\'s filter bar cell']",
    CONTACT_SEARCH_INPUT_ALT_1: "input[title='Address ID\\'s filter bar cell']",
    CONTACT_SEARCH_INPUT_ALT_2: "input[title='AddressID\\'s filter bar cell']",
    CONTACT_FILTER_SEARCH_INPUT: "input[id='AddressID_filterBarcell']",
    CONTACT_FILTER_SEARCH_INPUT_FILTER_BUTTON: "button.e-flmenu-okbtn",
    CONTACT_DISPLAYED_RECORDS: "tr.e-row td.e-rowcell",
    CONTACT_CONTEXT_MENU_OPTION: "div.e-contextmenu-wrapper li[role='menuitem']",
    CLICK_ON_CONTACT_DELETE_PROCEED_BUTTON: "div.vinspl-modal-body button[id^='ID_btnOk']",
}