export const projectLocator={
    PROJECT_ADD_BUTTON :"button[aria-label='Add']",
    PROJECT_CODE_INPUT :"input[name='ProjectCode']",
    PROJECT_NAME_INPUT_CELL :"tr.e-editedrow td[aria-label=' column header Name']",
    PROJECT_NAME_INPUT :"input[name='Name']",
    PROJECT_CATEGORY_PICKLIST :"div[id^='PicklistProjectCategoryName'] input",
    PROJECT_TYPE_PICKLIST : "input.vinspl-custom-fld",
    CATEGORY_SEARCH_INPUT :"input[name='CategoryVO.CategoryName']",
    PROJECT_TYPE_SEARCH_INPUT :"input[name='ProjectTypeVO.Name']",
    PROJECT_TYPE_FIRST_RESULT :"div.pickgrid  table.e-table tr.e-row:first-child",
    PROJECT_CATEGORY_PICKLIST_OK_BUTTON :"button[id^=btnOk]",
    PROJECT_TYPE_PICKLIST_OK_BUTTON :"button[id^=btnOk]",
    PROJECT_SAVE_BUTTON :"button[id^=btnSave]",
    PROJECT_CODE_SEARCH_FILTER_ICON :"th[data-colindex='4'] div.e-icon-filter",
    PROJECT_CODE_FILTER_SEARCH_INPUT :"input[id^='strui-grid-column']",
    PROJECT_FILTER_SEARCH_INPUT_FILTER_BUTTON :"div.e-footer-content button.e-flmenu-okbtn",
    CLICK_ON_PROJECT_DELETE_PROCEED_BUTTON :"button[id^='ID_btnOk']",
    PROJECT_TYPE: "div[id^='PicklistProjectTypeName'] input",
    PROJECT_TYPE_PICKLIST_INPUT:"input[name='ProjectTypeVO.Name']",
    PROJECT_TYPE_INPUT_PICKLIST_OK_BUTTON :"button[id^=btnSaveOk]",
    SUCCESS_MESSAGE_OK_BUTTON:"div#visplToastBackdrop div#visplToastOuter div#visplToast button",
    PROJECT_CONTEXT_MENU_OPTION:"div.e-contextmenu-wrapper li[role='menuitem']",
    PROJECT_EXPLORER_GRID_RECORDS:"td[aria-label*='column header Code']",
    }