export const locationPageLocators = {
    LOCATION_ADD_BUTTON :"button[aria-label='Add']",
    LOCATION_CODE_INPUT :"input[name='Code']",
    LOCATION_NAME_INPUT_CELL:"td[aria-label=' column header Name']",
    LOCATION_NAME_INPUT:"input[name='Name']",
    LOCATION_REMARKS_INPUT_CELL:"tr.vinspl-active-row td[aria-label=' column header Remarks']",
    LOCATION_REMARKS_INPUT :"input[name='Remarks']",
    LOCATION_BUNKER_CHECKBOX:"tr.vinspl-active-row td[aria-label='false column header Bunker Location'] div",
    LOCATION_BUNKER_CAPACITY_INPUT_CELL :"tr.vinspl-active-row [aria-label=' column header Bunker Capacity (M³)']",
    LOCATION_BUNKER_CAPACITY_INPUT:"tr.vinspl-active-row input[role='spinbutton']",
    LOCATION_FUNCTION_CHECKBOX :"tr.vinspl-active-row td[aria-label='false column header Function Location'] div",
    LOCATION_ITEM_CHECKBOX_CELL:"tr.vinspl-active-row td[aria-label='false column header Item Location']",
    LOCATION_ITEM_CHECKBOX :"tr.vinspl-active-row td[aria-label='false column header Item Location'] div.e-checkbox-wrapper",
    COMPONENT_LOCATION_CHECKBOX_CELL :"tr.vinspl-active-row td[aria-label='false column header Component Location']",
    COMPONENT_LOCATION_CHECKBOX :"tr.vinspl-active-row td[aria-label='false column header Component Location'] div.e-checkbox-wrapper",
    SHEQ_LOCATION_CHECKBOX_CELL :"tr.vinspl-active-row td[aria-label='false column header SHEQ Location']",
    SHEQ_LOCATION_CHECKBOX :"tr.vinspl-active-row td[aria-label='false column header SHEQ Location'] div.e-checkbox-wrapper",
    LOCATION_SAVE_BUTTON :"div.form-footer button[id^=btnSave]",
    LOCATION_EXIT_BUTTON :"div.form-footer button[id^=btnExit]",
    LOCATION_CODE_SEARCH_FILTER_ICON :"th[data-colindex='4'] div.e-icon-filter",
    LOCATION_CODE_FILTER_SEARCH_INPUT :"input[id^='strui-grid-column']",
    LOCATION_FILTER_SEARCH_INPUT_FILTER_BUTTON:"button.e-flmenu-okbtn",
    CLICK_ON_LOCATION_DELETE_PROCEED_BUTTON :"button[id^='ID_btnOk']",
}