export const rankFormLocators={
    RANK_NAME_INPUT:"input[name='Rank.Name']",
    GROUP_TYPE_PICKLIST:"div.vinspl-right-panel input[role='combobox']",
    SUB_GROUP_TYPE_PICKLIST :"input[name='Rank.SubGroup']",
    ROLE :"input[name='Rank.Role']",
    SAVE_BUTTON :"button.save",
    GROUP_TYPE_DROPDOWN:"div.vinspl-right-panel span[aria-label='dropdownlist']",
    GROUP_TYPE_WRAPPER :"//label[contains(normalize-space(),'Group Type')]" + "/ancestor::div[contains(@class,'vinspl-fld-grp')]" + "//span[contains(@class,'e-control-wrapper')]",
    GROUP_TYPE_INPUT :"//label[contains(normalize-space(),'Group Type')]/ancestor::div[contains(@class,'vinspl-fld-grp')]//input[contains(@class,'e-dropdownlist')]",
    SUB_GROUP_TYPE_SELECTION_SEARCH_BOX:"input[name='SubGroupTypeVO.SubGroupTypeName']",
    SUB_GROUP_TYPE_FIRST_RESULT:"table.e-table tr.e-row:first-child",
    ROLE_SELECTION_SEARCH_BOX :"input[name='PermRoleVO.PermRoleName']",
    ROLE_FIRST_RESULT:"table.e-table tr.e-row:first-child",
    RANK_SAVE_BUTTON :"button.save",
    RANK_SEARCH_INPUT :"input[title='Name\\'s filter bar cell']",
    RANK_SUB_GROUP_TYPE_MODAL_OK_BUTTON: "button[id^='btnSaveOk']",
    RANK_EXPLORER_CONTEXT_MENU_OPTION:"div.e-contextmenu-wrapper li[role='menuitem']",
    RANK_EXPLORER_DELETE_PROCEED_BUTON: "button[id^='ID_btnOk']",
};